x-api: &api
  image: ghcr.io/gb/jvmoonshot-xxvi:v28
  platform: linux/amd64
  environment: &api-env
    KDTREE_EARLY_DIST_MILLI: "161"
    KDTREE_REFINE_BOUNDARY: "1"
    KDTREE_PRIME_PLUNGE_CAP: "1"
    KDTREE_PRIME_BBOX: "0"
    KDTREE_RELAX_SOFT_CAP: "900"
    KDTREE_RELAX_RANGE: "700"
    KDTREE_RELAX_EPSILON: "0"
  volumes:
    - sockets:/sockets
  ulimits:
    nofile:
      soft: 65535
      hard: 65535
  deploy:
    resources:
      limits:
        cpus: "0.45"
        memory: "167M"

services:
  lb:
    image: ghcr.io/gb/lapada:v19
    platform: linux/amd64
    container_name: rinha-lb
    ports:
      - "9999:9999"
    environment:
      FD_UPSTREAMS: "/sockets/api1-fd.sock,/sockets/api2-fd.sock"
    volumes:
      - sockets:/sockets
    depends_on:
      - api1
      - api2
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "16M"

  api1:
    <<: *api
    container_name: rinha-api1
    environment:
      <<: *api-env
      LISTEN_SOCKET: /sockets/api1.sock
      FD_SOCKET: /sockets/api1-fd.sock

  api2:
    <<: *api
    container_name: rinha-api2
    environment:
      <<: *api-env
      LISTEN_SOCKET: /sockets/api2.sock
      FD_SOCKET: /sockets/api2-fd.sock

volumes:
  sockets:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=1m,mode=1777

networks:
  default:
    driver: bridge
